services:
  - type: web
    name: nys-virtual-campus
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
